name: aicup-2023-spring-nlp
channels:
  - nvidia/label/cuda-11.8.0
dependencies:
  - python=3.10
  - pip
  - pytorch::pytorch
  - pytorch::pytorch-cuda=11.8
  - pip:
      - datasets
      - elasticsearch
      - fire
      - hanlp
      - ipykernel
      - ipywidgets==7.7.1
      - lightning
      - opencc
      - safetensors
      - transformers
      - wandb
      - -e .
variables:
  HF_HOME: .cache
